version: '3'
services:
  redis:
    image: redis:5.0.3-alpine
    ports:
     - "6379:6379"
  db:
    image: mysql:8.0
    command:
      - --innodb_file_per_table
      - --character-set-server=utf8mb4
      - --default_authentication_plugin=mysql_native_password
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
